# strapi-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: strapi-secret
  namespace: web
type: Opaque
stringData:
  HOST: "0.0.0.0"
  PORT: "1337"
  NODE_ENV: production

  DATABASE_CLIENT: postgres
  DATABASE_HOST: postgres-service.database.svc.cluster.local
  DATABASE_PORT: "5432"
  DATABASE_NAME: cms
  DATABASE_USERNAME: postgres
  DATABASE_PASSWORD: ochuaren
  DATABASE_SSL: "false"

  APP_KEYS: J8cYl5bMF/Z7uUJ28dECXQ==,i2lJ3L5KPuDZ7aNLdK1UmA==,tzF65lkDYQung9FD+85u2Q==,BLtlB+fdgEOdFQo58U3i5Q==
  API_TOKEN_SALT: I8CL3OF1Xrjo0tEVeJMj+Q==
  ADMIN_JWT_SECRET: Hv2v2+ZhXxF9LxjTJk9PXA==
  JWT_SECRET: i5csoDbLkbsoVa4abJdcIQ==
  TRANSFER_TOKEN_SALT: i5csoDbLkbsoVa4abJdcIQ==
  ENCRYPTION_KEY: EuiYkLEinIXGLiM4K8xa7Q==
