apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
        - name: nextjs
          image: ghcr.io/ochuaren/ochuarenweb:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: NEXT_PUBLIC_STRAPI_API_URL
              value: "https://cms.ochuaren.com"
            - name: NEXT_PUBLIC_STRAPI_AUTH_TOKEN
              value: "2448c3db4ebbe382054109a70f3476c2144a76c6fbd14fac44148406287d1355ff6e36c873a195371066b54334b657968135cdcd27762b346e379c11f1948ed759753cc01fa56304dda836fbff9da5a17f4bb00ff2c656c41c7b0f95e31cefcd65b274b1ecd920b17d776753aa5e942f6529f10c47d727d4747084cb60bc4ee8"
            - name: AUTH_SECRET
              value: "abcdefghijklmnopqrstuvwxyz1234567890"
            - name: NEXTAUTH_URL
              value: "https://www.ochuaren.com"
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1
              memory: 512Mi
      imagePullSecrets:
        - name: ghcr-secret
